import java.util.Arrays;
import java.util.List;
import java.util.TreeSet;
import java.io.PrintWriter;
import java.io.FileWriter;
import kodkod.ast.*;
import kodkod.ast.operator.*;
import kodkod.instance.*;
import kodkod.engine.*;
import kodkod.engine.satlab.SATFactory;
import kodkod.engine.config.Options;

import edu.mit.csail.sdg.moolloy.solver.kodkod.api.*;

public final class Test {

static Relation x0;
static Relation x1;
static Relation x2;
static Relation x3;
static Relation x4;
static Relation x5;
static Relation x6;
static Relation x7;
static Relation x8;
static Relation x9;
static Relation x10;
static Relation x11;
static Relation x12;
static Relation x13;
static Relation x14;
static Relation x15;
static Relation x16;
static Relation x17;
static Relation x18;
static Relation x19;
static Relation x20;
static Relation x21;
static Relation x22;
static Relation x23;
static Relation x24;
static Relation x25;
static Relation x26;
static List<String> atomlist;
static Universe universe;
static TupleFactory factory;
static Bounds bounds;
static TupleSet x0_upper;
static TupleSet x1_upper;
static TupleSet x2_upper;
static TupleSet x3_upper;
static TupleSet x4_upper;
static TupleSet x5_upper;
static TupleSet x6_upper;
static TupleSet x7_upper;
static TupleSet x8_upper;
static TupleSet x9_upper;
static TupleSet x10_upper;
static TupleSet x11_upper;
static TupleSet x12_upper;
static TupleSet x13_upper;
static TupleSet x14_upper;
static TupleSet x15_upper;
static TupleSet x16_upper;
static TupleSet x17_upper;
static TupleSet x18_upper;
static TupleSet x19_upper;
static TupleSet x20_upper;
static TupleSet x21_upper;
static TupleSet x22_upper;
static TupleSet x23_upper;
static TupleSet x24_upper;
static TupleSet x25_upper;
static TupleSet x26_upper;
static TreeSet<Objective> objectives;
static Expression x28;
static IntExpression x27;
static Objective o0;
static Expression x30;
static IntExpression x29;
static Objective o1;
static Expression x33;
static Formula x32;
static Expression x36;
static Expression x35;
static Formula x34;
static Expression x39;
static Expression x38;
static Formula x37;
static Expression x42;
static Expression x41;
static Formula x40;
static Expression x45;
static Expression x44;
static Formula x43;
static Expression x48;
static Expression x47;
static Formula x46;
static Expression x51;
static Expression x50;
static Formula x49;
static Expression x54;
static Expression x53;
static Formula x52;
static Expression x58;
static IntExpression x60;
static Expression x59;
static Formula x57;
static Expression x63;
static IntExpression x65;
static Expression x64;
static Formula x62;
static Expression x67;
static IntExpression x69;
static Expression x68;
static Formula x66;
static Formula x61;
static Formula x56;
static Expression x71;
static IntExpression x73;
static Expression x72;
static Formula x70;
static Formula x55;
static Expression x77;
static IntExpression x79;
static Expression x78;
static Formula x76;
static Expression x82;
static IntExpression x84;
static Expression x83;
static Formula x81;
static Expression x86;
static IntExpression x88;
static Expression x87;
static Formula x85;
static Formula x80;
static Formula x75;
static Expression x90;
static IntExpression x92;
static Expression x91;
static Formula x89;
static Formula x74;
static Expression x96;
static IntExpression x98;
static Expression x97;
static Formula x95;
static Expression x101;
static IntExpression x103;
static Expression x102;
static Formula x100;
static Expression x105;
static IntExpression x107;
static Expression x106;
static Formula x104;
static Formula x99;
static Formula x94;
static Expression x109;
static IntExpression x111;
static Expression x110;
static Formula x108;
static Formula x93;
static Expression x115;
static IntExpression x117;
static Expression x116;
static Formula x114;
static Expression x120;
static IntExpression x122;
static Expression x121;
static Formula x119;
static Expression x124;
static IntExpression x126;
static Expression x125;
static Formula x123;
static Formula x118;
static Formula x113;
static Expression x128;
static IntExpression x130;
static Expression x129;
static Formula x127;
static Formula x112;
static Expression x134;
static IntExpression x136;
static Expression x135;
static Formula x133;
static Expression x139;
static IntExpression x141;
static Expression x140;
static Formula x138;
static Expression x143;
static IntExpression x145;
static Expression x144;
static Formula x142;
static Formula x137;
static Formula x132;
static Expression x147;
static IntExpression x149;
static Expression x148;
static Formula x146;
static Formula x131;
static Expression x153;
static IntExpression x155;
static Expression x154;
static Formula x152;
static Expression x158;
static IntExpression x160;
static Expression x159;
static Formula x157;
static Expression x162;
static IntExpression x164;
static Expression x163;
static Formula x161;
static Formula x156;
static Formula x151;
static Expression x166;
static IntExpression x168;
static Expression x167;
static Formula x165;
static Formula x150;
static Expression x172;
static IntExpression x174;
static Expression x173;
static Formula x171;
static Expression x177;
static IntExpression x179;
static Expression x178;
static Formula x176;
static Expression x181;
static IntExpression x183;
static Expression x182;
static Formula x180;
static Formula x175;
static Formula x170;
static Expression x185;
static IntExpression x187;
static Expression x186;
static Formula x184;
static Formula x169;
static Expression x191;
static IntExpression x193;
static Expression x192;
static Formula x190;
static Expression x196;
static IntExpression x198;
static Expression x197;
static Formula x195;
static Expression x200;
static IntExpression x202;
static Expression x201;
static Formula x199;
static Formula x194;
static Formula x189;
static Expression x204;
static IntExpression x206;
static Expression x205;
static Formula x203;
static Formula x188;
static Expression x210;
static IntExpression x212;
static Expression x211;
static Formula x209;
static Expression x215;
static IntExpression x217;
static Expression x216;
static Formula x214;
static Expression x219;
static IntExpression x221;
static Expression x220;
static Formula x218;
static Formula x213;
static Formula x208;
static Expression x223;
static IntExpression x225;
static Expression x224;
static Formula x222;
static Formula x207;
static Variable x228;
static Expression x229;
static Decls x227;
static Expression x232;
static Formula x231;
static Formula x233;
static Formula x230;
static Formula x226;
static Expression x236;
static Formula x235;
static Variable x240;
static Decls x239;
static Expression x243;
static Formula x242;
static Formula x244;
static Formula x241;
static Formula x238;
static Expression x246;
static Formula x245;
static Variable x249;
static Decls x248;
static Expression x252;
static Formula x251;
static Formula x253;
static Formula x250;
static Formula x247;
static Expression x255;
static Formula x254;
static Variable x258;
static Decls x257;
static Expression x261;
static Formula x260;
static Formula x262;
static Formula x259;
static Formula x256;
static Expression x264;
static Formula x263;
static Variable x267;
static Decls x266;
static Expression x270;
static Formula x269;
static Formula x271;
static Formula x268;
static Formula x265;
static Expression x273;
static Formula x272;
static Variable x276;
static Decls x275;
static Expression x279;
static Formula x278;
static Formula x280;
static Formula x277;
static Formula x274;
static Expression x282;
static Formula x281;
static Variable x285;
static Decls x284;
static Expression x287;
static Formula x286;
static Formula x283;
static Expression x289;
static Formula x288;
static Variable x292;
static Decls x291;
static Expression x294;
static Formula x293;
static Formula x290;
static Expression x296;
static Formula x295;
static Variable x299;
static Decls x298;
static Expression x302;
static Formula x301;
static Formula x303;
static Formula x300;
static Formula x297;
static Expression x305;
static Formula x304;
static Variable x308;
static Decls x307;
static Expression x311;
static Formula x310;
static Formula x312;
static Formula x309;
static Formula x306;
static Expression x314;
static Formula x313;
static Variable x318;
static Decls x317;
static Variable x320;
static Decls x319;
static Decls x316;
static Expression x323;
static Formula x322;
static Expression x325;
static Formula x324;
static Formula x321;
static Formula x315;
static Variable x329;
static Decls x328;
static Variable x331;
static Decls x330;
static Decls x327;
static Expression x335;
static Formula x334;
static Formula x333;
static Variable x338;
static Expression x339;
static Decls x337;
static Expression x341;
static Formula x340;
static Formula x336;
static Formula x332;
static Formula x326;
static Variable x345;
static Decls x344;
static Variable x347;
static Decls x346;
static Decls x343;
static Expression x349;
static Expression x350;
static Formula x348;
static Formula x342;
static Expression x352;
static Formula x351;
static Variable x356;
static Decls x355;
static Variable x358;
static Expression x359;
static Decls x357;
static Variable x361;
static Expression x362;
static Decls x360;
static Decls x354;
static Expression x367;
static Expression x366;
static Expression x369;
static Expression x368;
static Formula x365;
static Formula x364;
static Formula x370;
static Formula x363;
static Formula x353;
static Variable x374;
static Decls x373;
static Variable x376;
static Expression x377;
static Decls x375;
static Variable x379;
static Expression x380;
static Decls x378;
static Decls x372;
static Expression x385;
static Expression x384;
static Expression x387;
static Expression x386;
static Formula x383;
static Formula x382;
static Formula x388;
static Formula x381;
static Formula x371;
static Variable x391;
static Decls x390;
static Expression x393;
static Variable x397;
static Expression x398;
static Decls x396;
static Expression x400;
static IntExpression x399;
static Formula x395;
static Expression x394;
static Formula x392;
static Formula x389;
static Variable x403;
static Decls x402;
static Expression x405;
static Variable x409;
static Expression x410;
static Decls x408;
static Expression x412;
static IntExpression x411;
static Formula x407;
static Expression x406;
static Formula x404;
static Formula x401;
static Formula x413;
static Formula x414;
static Formula x415;
static Formula x416;
static Formula x417;
static Formula x418;
static Formula x419;
static Formula x420;
static Formula x421;
static Formula x422;
static Formula x423;
static Formula x424;
static Formula x425;
static Formula x426;
static Formula x427;
static Formula x428;
static Formula x429;
static Formula x430;
static Formula x431;
static Formula x432;
static Formula x433;
static Formula x434;
static Formula x435;
static Formula x436;
static Formula x437;
static Formula x438;
static Formula x439;
static Formula x31;
static void Do_0(){x0 = Relation.unary("Int/min");
x1 = Relation.unary("Int/zero");
x2 = Relation.unary("Int/max");
x3 = Relation.nary("Int/next", 2);
x4 = Relation.unary("seq/Int");
x5 = Relation.unary("String");
x6 = Relation.unary("this/position_0_0");
x7 = Relation.unary("this/position_0_1");
x8 = Relation.unary("this/position_0_2");
x9 = Relation.unary("this/position_1_0");
x10 = Relation.unary("this/position_1_1");
x11 = Relation.unary("this/position_1_2");
x12 = Relation.unary("this/position_2_0");
x13 = Relation.unary("this/position_2_1");
x14 = Relation.unary("this/position_2_2");
x15 = Relation.unary("this/Rook");
x16 = Relation.unary("this/ConcreteBoard");
x17 = Relation.nary("this/Position.row", 2);
x18 = Relation.nary("this/Position.col", 2);
x19 = Relation.nary("this/Position.score1", 2);
}
static void Do_1(){x20 = Relation.nary("this/Position.score2", 2);
x21 = Relation.nary("this/Rook.board", 2);
x22 = Relation.nary("this/Rook.position", 2);
x23 = Relation.nary("this/Board.pieces", 2);
x24 = Relation.nary("this/Board.positions", 2);
x25 = Relation.nary("this/Board.score1", 2);
x26 = Relation.nary("this/Board.score2", 2);
atomlist = Arrays.asList( "-1", "-10", "-11", "-12", "-13", "-14", "-15", "-16", "-2", "-3", "-4", "-5", "-6", "-7", "-8", "-9", "0", "1", "10", "11", "12", "13", "14", "15", "2", "3", "4", "5", "6", "7", "8", "9", "ConcreteBoard$0", "Rook$0", "Rook$1", "Rook$2", "position_0_0$0", "position_0_1$0", "position_0_2$0", "position_1_0$0", "position_1_1$0", "position_1_2$0", "position_2_0$0", "position_2_1$0", "position_2_2$0");
universe = new Universe(atomlist);
factory = universe.factory();
bounds = new Bounds(universe);
x0_upper = factory.noneOf(1);
x0_upper.add(factory.tuple("-16"));
bounds.boundExactly(x0, x0_upper);


x1_upper = factory.noneOf(1);
x1_upper.add(factory.tuple("0"));
bounds.boundExactly(x1, x1_upper);


x2_upper = factory.noneOf(1);
x2_upper.add(factory.tuple("15"));
bounds.boundExactly(x2, x2_upper);


}
static void Do_2(){x3_upper = factory.noneOf(2);
x3_upper.add(factory.tuple("-16").product(factory.tuple("-15")));
x3_upper.add(factory.tuple("-15").product(factory.tuple("-14")));
x3_upper.add(factory.tuple("-14").product(factory.tuple("-13")));
x3_upper.add(factory.tuple("-13").product(factory.tuple("-12")));
x3_upper.add(factory.tuple("-12").product(factory.tuple("-11")));
x3_upper.add(factory.tuple("-11").product(factory.tuple("-10")));
x3_upper.add(factory.tuple("-10").product(factory.tuple("-9")));
x3_upper.add(factory.tuple("-9").product(factory.tuple("-8")));
x3_upper.add(factory.tuple("-8").product(factory.tuple("-7")));
x3_upper.add(factory.tuple("-7").product(factory.tuple("-6")));
x3_upper.add(factory.tuple("-6").product(factory.tuple("-5")));
x3_upper.add(factory.tuple("-5").product(factory.tuple("-4")));
x3_upper.add(factory.tuple("-4").product(factory.tuple("-3")));
x3_upper.add(factory.tuple("-3").product(factory.tuple("-2")));
x3_upper.add(factory.tuple("-2").product(factory.tuple("-1")));
x3_upper.add(factory.tuple("-1").product(factory.tuple("0")));
x3_upper.add(factory.tuple("0").product(factory.tuple("1")));
x3_upper.add(factory.tuple("1").product(factory.tuple("2")));
x3_upper.add(factory.tuple("2").product(factory.tuple("3")));
}
static void Do_3(){x3_upper.add(factory.tuple("3").product(factory.tuple("4")));
x3_upper.add(factory.tuple("4").product(factory.tuple("5")));
x3_upper.add(factory.tuple("5").product(factory.tuple("6")));
x3_upper.add(factory.tuple("6").product(factory.tuple("7")));
x3_upper.add(factory.tuple("7").product(factory.tuple("8")));
x3_upper.add(factory.tuple("8").product(factory.tuple("9")));
x3_upper.add(factory.tuple("9").product(factory.tuple("10")));
x3_upper.add(factory.tuple("10").product(factory.tuple("11")));
x3_upper.add(factory.tuple("11").product(factory.tuple("12")));
x3_upper.add(factory.tuple("12").product(factory.tuple("13")));
x3_upper.add(factory.tuple("13").product(factory.tuple("14")));
x3_upper.add(factory.tuple("14").product(factory.tuple("15")));
bounds.boundExactly(x3, x3_upper);


x4_upper = factory.noneOf(1);
x4_upper.add(factory.tuple("0"));
x4_upper.add(factory.tuple("1"));
x4_upper.add(factory.tuple("2"));
x4_upper.add(factory.tuple("3"));
bounds.boundExactly(x4, x4_upper);


x5_upper = factory.noneOf(1);
}
static void Do_4(){bounds.boundExactly(x5, x5_upper);


x6_upper = factory.noneOf(1);
x6_upper.add(factory.tuple("position_0_0$0"));
bounds.boundExactly(x6, x6_upper);


x7_upper = factory.noneOf(1);
x7_upper.add(factory.tuple("position_0_1$0"));
bounds.boundExactly(x7, x7_upper);


x8_upper = factory.noneOf(1);
x8_upper.add(factory.tuple("position_0_2$0"));
bounds.boundExactly(x8, x8_upper);


x9_upper = factory.noneOf(1);
x9_upper.add(factory.tuple("position_1_0$0"));
bounds.boundExactly(x9, x9_upper);


x10_upper = factory.noneOf(1);
x10_upper.add(factory.tuple("position_1_1$0"));
bounds.boundExactly(x10, x10_upper);


x11_upper = factory.noneOf(1);
x11_upper.add(factory.tuple("position_1_2$0"));
bounds.boundExactly(x11, x11_upper);


x12_upper = factory.noneOf(1);
}
static void Do_5(){x12_upper.add(factory.tuple("position_2_0$0"));
bounds.boundExactly(x12, x12_upper);


x13_upper = factory.noneOf(1);
x13_upper.add(factory.tuple("position_2_1$0"));
bounds.boundExactly(x13, x13_upper);


x14_upper = factory.noneOf(1);
x14_upper.add(factory.tuple("position_2_2$0"));
bounds.boundExactly(x14, x14_upper);


x15_upper = factory.noneOf(1);
x15_upper.add(factory.tuple("Rook$0"));
x15_upper.add(factory.tuple("Rook$1"));
x15_upper.add(factory.tuple("Rook$2"));
bounds.boundExactly(x15, x15_upper);


x16_upper = factory.noneOf(1);
x16_upper.add(factory.tuple("ConcreteBoard$0"));
bounds.boundExactly(x16, x16_upper);


x17_upper = factory.noneOf(2);
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-16")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-15")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-14")));
}
static void Do_6(){x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-13")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-12")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-11")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-10")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-9")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-8")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-7")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-6")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-5")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-4")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-3")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-2")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-1")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("0")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("1")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("2")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("3")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("4")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("5")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("6")));
}
static void Do_7(){x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("7")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("8")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("9")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("10")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("11")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("12")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("13")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("14")));
x17_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("15")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-16")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-15")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-14")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-13")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-12")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-11")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-10")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-9")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-8")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-7")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-6")));
}
static void Do_8(){x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-5")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-4")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-3")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-2")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-1")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("0")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("1")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("2")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("3")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("4")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("5")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("6")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("7")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("8")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("9")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("10")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("11")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("12")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("13")));
x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("14")));
}
static void Do_9(){x17_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("15")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("-16")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("-15")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("-14")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("-13")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("-12")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("-11")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("-10")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("-9")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("-8")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("-7")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("-6")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("-5")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("-4")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("-3")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("-2")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("-1")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("0")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("1")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("2")));
}
static void Do_10(){x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("3")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("4")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("5")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("6")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("7")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("8")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("9")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("10")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("11")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("12")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("13")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("14")));
x17_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("15")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("-16")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("-15")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("-14")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("-13")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("-12")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("-11")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("-10")));
}
static void Do_11(){x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("-9")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("-8")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("-7")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("-6")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("-5")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("-4")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("-3")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("-2")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("-1")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("0")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("1")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("2")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("3")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("4")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("5")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("6")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("7")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("8")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("9")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("10")));
}
static void Do_12(){x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("11")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("12")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("13")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("14")));
x17_upper.add(factory.tuple("position_1_0$0").product(factory.tuple("15")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("-16")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("-15")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("-14")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("-13")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("-12")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("-11")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("-10")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("-9")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("-8")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("-7")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("-6")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("-5")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("-4")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("-3")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("-2")));
}
static void Do_13(){x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("-1")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("0")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("1")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("2")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("3")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("4")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("5")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("6")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("7")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("8")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("9")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("10")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("11")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("12")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("13")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("14")));
x17_upper.add(factory.tuple("position_1_1$0").product(factory.tuple("15")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("-16")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("-15")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("-14")));
}
static void Do_14(){x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("-13")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("-12")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("-11")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("-10")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("-9")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("-8")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("-7")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("-6")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("-5")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("-4")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("-3")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("-2")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("-1")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("0")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("1")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("2")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("3")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("4")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("5")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("6")));
}
static void Do_15(){x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("7")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("8")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("9")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("10")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("11")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("12")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("13")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("14")));
x17_upper.add(factory.tuple("position_1_2$0").product(factory.tuple("15")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("-16")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("-15")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("-14")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("-13")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("-12")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("-11")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("-10")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("-9")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("-8")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("-7")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("-6")));
}
static void Do_16(){x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("-5")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("-4")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("-3")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("-2")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("-1")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("0")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("1")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("2")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("3")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("4")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("5")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("6")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("7")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("8")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("9")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("10")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("11")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("12")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("13")));
x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("14")));
}
static void Do_17(){x17_upper.add(factory.tuple("position_2_0$0").product(factory.tuple("15")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("-16")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("-15")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("-14")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("-13")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("-12")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("-11")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("-10")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("-9")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("-8")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("-7")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("-6")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("-5")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("-4")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("-3")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("-2")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("-1")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("0")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("1")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("2")));
}
static void Do_18(){x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("3")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("4")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("5")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("6")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("7")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("8")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("9")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("10")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("11")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("12")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("13")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("14")));
x17_upper.add(factory.tuple("position_2_1$0").product(factory.tuple("15")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("-16")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("-15")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("-14")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("-13")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("-12")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("-11")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("-10")));
}
static void Do_19(){x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("-9")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("-8")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("-7")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("-6")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("-5")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("-4")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("-3")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("-2")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("-1")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("0")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("1")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("2")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("3")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("4")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("5")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("6")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("7")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("8")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("9")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("10")));
}
static void Do_20(){x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("11")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("12")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("13")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("14")));
x17_upper.add(factory.tuple("position_2_2$0").product(factory.tuple("15")));
bounds.bound(x17, x17_upper);


x18_upper = factory.noneOf(2);
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-16")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-15")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-14")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-13")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-12")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-11")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-10")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-9")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-8")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-7")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-6")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-5")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-4")));
}
static void Do_21(){x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-3")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-2")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("-1")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("0")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("1")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("2")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("3")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("4")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("5")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("6")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("7")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("8")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("9")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("10")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("11")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("12")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("13")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("14")));
x18_upper.add(factory.tuple("position_0_0$0").product(factory.tuple("15")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-16")));
}
static void Do_22(){x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-15")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-14")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-13")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-12")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-11")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-10")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-9")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-8")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-7")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-6")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-5")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-4")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-3")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-2")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("-1")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("0")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("1")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("2")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("3")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("4")));
}
static void Do_23(){x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("5")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("6")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("7")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("8")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("9")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("10")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("11")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("12")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("13")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("14")));
x18_upper.add(factory.tuple("position_0_1$0").product(factory.tuple("15")));
x18_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("-16")));
x18_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("-15")));
x18_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("-14")));
x18_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("-13")));
x18_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("-12")));
x18_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("-11")));
x18_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("-10")));
x18_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("-9")));
x18_upper.add(factory.tuple("position_0_2$0").product(factory.tuple("-8")));
}
public static void main(String[] args) throws Exception {

Do_0();
Do_1();
Do_2();
Do_3();
Do_4();
Do_5();
Do_6();
Do_7();
Do_8();
Do_9();
Do_10();
Do_11();
Do_12();
Do_13();
Do_14();
Do_15();
Do_16();
Do_17();
Do_18();
Do_19();
Do_20();
Do_21();
Do_22();
Do_23();

MultiObjectiveProblem problem = new MultiObjectiveProblem(bounds, 5, x31, objectives);
GuidedImprovementAlgorithm gia = new GuidedImprovementAlgorithm("asdf", false);
SolutionNotifier notifier = new SolutionNotifier() {
int solution_count;
public void tell(final MeasuredSolution s) {
try {
FileWriter file = new FileWriter("kodkod_solutions_" + solution_count + ".txt");
PrintWriter print = new PrintWriter(file);
print.println(s.toString());
solution_count += 1;
print.flush();
print.close();
file.close();
} catch (Exception e) {}
}
public void tell(Solution s, MetricPoint values) {
tell(new MeasuredSolution(s, values));
}
public void done(){};
};
System.out.println("Solving...");
System.out.flush();
gia.moosolve(problem, notifier, true);
}}
