/* The following code was generated by JFlex 1.4.1 on 3/30/12 2:44 PM */

// Alloy Analyzer 4 -- Copyright (c) 2006-2008, Felix Chang
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files
// (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify,
// merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
// LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF
// OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

package edu.mit.csail.sdg.alloy4compiler.parser;

import edu.mit.csail.sdg.alloy4.Err;
import edu.mit.csail.sdg.alloy4.ErrorSyntax;
import edu.mit.csail.sdg.alloy4.Pos;
import edu.mit.csail.sdg.alloy4.Version;
import edu.mit.csail.sdg.alloy4compiler.ast.ExprConstant;
import edu.mit.csail.sdg.alloy4compiler.ast.ExprVar;
import java.util.List;
import java_cup.runtime.*;

/** Autogenerated by JFlex 1.4.1 */


public final class CompLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\72\1\74\1\65\1\0\1\74\1\73\16\72\4\0\1\74\1\1"+
    "\1\63\1\2\1\71\1\0\1\3\1\66\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\13\1\14\12\67\1\15\1\0\1\16\1\17\1\12"+
    "\1\0\1\20\10\71\1\56\11\71\1\62\7\71\1\21\1\64\1\22"+
    "\1\23\1\71\1\0\1\30\1\31\1\35\1\40\1\41\1\55\1\61"+
    "\1\44\1\42\1\46\1\45\1\36\1\50\1\37\1\47\1\54\1\60"+
    "\1\34\1\32\1\33\1\43\1\53\1\71\1\51\1\52\1\57\1\24"+
    "\1\25\1\26\1\27\41\72\2\0\4\70\4\0\1\70\2\0\1\72"+
    "\7\0\1\70\4\0\1\70\5\0\27\70\1\0\37\70\1\0\u013f\70"+
    "\31\0\162\70\4\0\14\70\16\0\5\70\11\0\1\70\21\0\130\72"+
    "\5\0\23\72\12\0\1\70\13\0\1\70\1\0\3\70\1\0\1\70"+
    "\1\0\24\70\1\0\54\70\1\0\46\70\1\0\5\70\4\0\202\70"+
    "\1\0\4\72\3\0\105\70\1\0\46\70\2\0\2\70\6\0\20\70"+
    "\41\0\46\70\2\0\1\70\7\0\47\70\11\0\21\72\1\0\27\72"+
    "\1\0\3\72\1\0\1\72\1\0\2\72\1\0\1\72\13\0\33\70"+
    "\5\0\3\70\15\0\4\72\14\0\6\72\13\0\32\70\5\0\13\70"+
    "\16\72\7\0\12\72\4\0\2\70\1\72\143\70\1\0\1\70\10\72"+
    "\1\0\6\72\2\70\2\72\1\0\4\72\2\70\12\72\3\70\2\0"+
    "\1\70\17\0\1\72\1\70\1\72\36\70\33\72\2\0\3\70\60\0"+
    "\46\70\13\72\1\70\u014f\0\3\72\66\70\2\0\1\72\1\70\20\72"+
    "\2\0\1\70\4\72\3\0\12\70\2\72\2\0\12\72\21\0\3\72"+
    "\1\0\10\70\2\0\2\70\2\0\26\70\1\0\7\70\1\0\1\70"+
    "\3\0\4\70\2\0\1\72\1\70\7\72\2\0\2\72\2\0\3\72"+
    "\11\0\1\72\4\0\2\70\1\0\3\70\2\72\2\0\12\72\4\70"+
    "\15\0\3\72\1\0\6\70\4\0\2\70\2\0\26\70\1\0\7\70"+
    "\1\0\2\70\1\0\2\70\1\0\2\70\2\0\1\72\1\0\5\72"+
    "\4\0\2\72\2\0\3\72\13\0\4\70\1\0\1\70\7\0\14\72"+
    "\3\70\14\0\3\72\1\0\11\70\1\0\3\70\1\0\26\70\1\0"+
    "\7\70\1\0\2\70\1\0\5\70\2\0\1\72\1\70\10\72\1\0"+
    "\3\72\1\0\3\72\2\0\1\70\17\0\2\70\2\72\2\0\12\72"+
    "\1\0\1\70\17\0\3\72\1\0\10\70\2\0\2\70\2\0\26\70"+
    "\1\0\7\70\1\0\2\70\1\0\5\70\2\0\1\72\1\70\6\72"+
    "\3\0\2\72\2\0\3\72\10\0\2\72\4\0\2\70\1\0\3\70"+
    "\4\0\12\72\1\0\1\70\20\0\1\72\1\70\1\0\6\70\3\0"+
    "\3\70\1\0\4\70\3\0\2\70\1\0\1\70\1\0\2\70\3\0"+
    "\2\70\3\0\3\70\3\0\10\70\1\0\3\70\4\0\5\72\3\0"+
    "\3\72\1\0\4\72\11\0\1\72\17\0\11\72\11\0\1\70\7\0"+
    "\3\72\1\0\10\70\1\0\3\70\1\0\27\70\1\0\12\70\1\0"+
    "\5\70\4\0\7\72\1\0\3\72\1\0\4\72\7\0\2\72\11\0"+
    "\2\70\4\0\12\72\22\0\2\72\1\0\10\70\1\0\3\70\1\0"+
    "\27\70\1\0\12\70\1\0\5\70\2\0\1\72\1\70\7\72\1\0"+
    "\3\72\1\0\4\72\7\0\2\72\7\0\1\70\1\0\2\70\4\0"+
    "\12\72\22\0\2\72\1\0\10\70\1\0\3\70\1\0\27\70\1\0"+
    "\20\70\4\0\6\72\2\0\3\72\1\0\4\72\11\0\1\72\10\0"+
    "\2\70\4\0\12\72\22\0\2\72\1\0\22\70\3\0\30\70\1\0"+
    "\11\70\1\0\1\70\2\0\7\70\3\0\1\72\4\0\6\72\1\0"+
    "\1\72\1\0\10\72\22\0\2\72\15\0\60\70\1\72\2\70\7\72"+
    "\4\0\10\70\10\72\1\0\12\72\47\0\2\70\1\0\1\70\2\0"+
    "\2\70\1\0\1\70\2\0\1\70\6\0\4\70\1\0\7\70\1\0"+
    "\3\70\1\0\1\70\1\0\1\70\2\0\2\70\1\0\4\70\1\72"+
    "\2\70\6\72\1\0\2\72\1\70\2\0\5\70\1\0\1\70\1\0"+
    "\6\72\2\0\12\72\2\0\2\70\42\0\1\70\27\0\2\72\6\0"+
    "\12\72\13\0\1\72\1\0\1\72\1\0\1\72\4\0\2\72\10\70"+
    "\1\0\42\70\6\0\24\72\1\0\2\72\4\70\4\0\10\72\1\0"+
    "\44\72\11\0\1\72\71\0\42\70\1\0\5\70\1\0\2\70\1\0"+
    "\7\72\3\0\4\72\6\0\12\72\6\0\6\70\4\72\106\0\46\70"+
    "\12\0\51\70\7\0\132\70\5\0\104\70\5\0\122\70\6\0\7\70"+
    "\1\0\77\70\1\0\1\70\1\0\4\70\2\0\7\70\1\0\1\70"+
    "\1\0\4\70\2\0\47\70\1\0\1\70\1\0\4\70\2\0\37\70"+
    "\1\0\1\70\1\0\4\70\2\0\7\70\1\0\1\70\1\0\4\70"+
    "\2\0\7\70\1\0\7\70\1\0\27\70\1\0\37\70\1\0\1\70"+
    "\1\0\4\70\2\0\7\70\1\0\47\70\1\0\23\70\16\0\11\72"+
    "\56\0\125\70\14\0\u026c\70\2\0\10\70\12\0\32\70\5\0\113\70"+
    "\3\0\3\70\17\0\15\70\1\0\4\70\3\72\13\0\22\70\3\72"+
    "\13\0\22\70\2\72\14\0\15\70\1\0\3\70\1\0\2\72\14\0"+
    "\64\70\40\72\3\0\1\70\3\0\2\70\1\72\2\0\12\72\41\0"+
    "\3\72\2\0\12\72\6\0\130\70\10\0\51\70\1\72\126\0\35\70"+
    "\3\0\14\72\4\0\14\72\12\0\12\72\36\70\2\0\5\70\u038b\0"+
    "\154\70\224\0\234\70\4\0\132\70\6\0\26\70\2\0\6\70\2\0"+
    "\46\70\2\0\6\70\2\0\10\70\1\0\1\70\1\0\1\70\1\0"+
    "\1\70\1\0\37\70\2\0\65\70\1\0\7\70\1\0\1\70\3\0"+
    "\3\70\1\0\7\70\3\0\4\70\2\0\6\70\4\0\15\70\5\0"+
    "\3\70\1\0\7\70\17\0\4\72\32\0\5\72\20\0\2\70\23\0"+
    "\1\70\13\0\4\72\6\0\6\72\1\0\1\70\15\0\1\70\40\0"+
    "\22\70\36\0\15\72\4\0\1\72\3\0\6\72\27\0\1\70\4\0"+
    "\1\70\2\0\12\70\1\0\1\70\3\0\5\70\6\0\1\70\1\0"+
    "\1\70\1\0\1\70\1\0\4\70\1\0\3\70\1\0\7\70\3\0"+
    "\3\70\5\0\5\70\26\0\44\70\u0e81\0\3\70\31\0\11\70\6\72"+
    "\1\0\5\70\2\0\5\70\4\0\126\70\2\0\2\72\2\0\3\70"+
    "\1\0\137\70\5\0\50\70\4\0\136\70\21\0\30\70\70\0\20\70"+
    "\u0200\0\u19b6\70\112\0\u51a6\70\132\0\u048d\70\u0773\0\u2ba4\70\u215c\0\u012e\70"+
    "\2\0\73\70\225\0\7\70\14\0\5\70\5\0\1\70\1\72\12\70"+
    "\1\0\15\70\1\0\5\70\1\0\1\70\1\0\2\70\1\0\2\70"+
    "\1\0\154\70\41\0\u016b\70\22\0\100\70\2\0\66\70\50\0\15\70"+
    "\3\0\20\72\20\0\4\72\17\0\2\70\30\0\3\70\31\0\1\70"+
    "\6\0\5\70\1\0\207\70\2\0\1\72\4\0\1\70\13\0\12\72"+
    "\7\0\32\70\4\0\1\70\1\0\32\70\12\0\132\70\3\0\6\70"+
    "\2\0\6\70\2\0\6\70\2\0\3\70\3\0\2\70\3\0\2\70"+
    "\22\0\3\72\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\23\31\1\32\1\33\1\34\1\35\1\36\1\33"+
    "\1\37\1\40\1\41\1\0\1\42\1\43\1\44\1\45"+
    "\1\46\1\45\1\47\1\31\1\50\14\31\1\51\4\31"+
    "\1\52\5\31\1\47\14\31\1\53\1\0\1\54\1\55"+
    "\2\0\1\56\2\31\1\57\1\35\1\60\1\61\1\62"+
    "\1\63\1\64\2\31\1\65\1\31\1\66\1\31\1\2"+
    "\6\31\1\67\2\31\1\70\3\31\1\56\2\31\1\71"+
    "\11\31\1\72\1\73\1\74\1\31\1\75\1\0\1\33"+
    "\2\31\1\76\1\77\1\31\1\100\1\101\1\102\1\103"+
    "\1\104\4\31\1\105\1\31\1\106\1\31\1\107\2\31"+
    "\1\110\3\31\1\111\1\112\1\31\1\113\3\31\1\114"+
    "\20\31\1\115\4\31\1\116\6\31\1\117\2\31\1\120"+
    "\2\31\1\121\1\122\1\31\1\123\1\46\5\31\1\124"+
    "\1\125\1\102\2\31\1\126\1\127\1\130\3\31\1\111"+
    "\1\67\1\131";

  private static int [] zzUnpackAction() {
    int [] result = new int[246];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\75\0\75\0\75\0\172\0\75\0\75\0\75"+
    "\0\267\0\75\0\364\0\u0131\0\75\0\u016e\0\u01ab\0\u01e8"+
    "\0\u0225\0\75\0\75\0\75\0\75\0\75\0\u0262\0\75"+
    "\0\75\0\u029f\0\u02dc\0\u0319\0\u0356\0\u0393\0\u03d0\0\u040d"+
    "\0\u044a\0\u0487\0\u04c4\0\u0501\0\u053e\0\u057b\0\u05b8\0\u05f5"+
    "\0\u0632\0\u066f\0\u06ac\0\u06e9\0\u0726\0\75\0\u0763\0\75"+
    "\0\75\0\u07a0\0\75\0\u07dd\0\75\0\u081a\0\75\0\75"+
    "\0\75\0\u0857\0\75\0\75\0\75\0\u0894\0\u08d1\0\u090e"+
    "\0\u094b\0\u0988\0\u09c5\0\u0a02\0\u0a3f\0\u0a7c\0\u0ab9\0\u0af6"+
    "\0\u0b33\0\u0b70\0\u0bad\0\u0bea\0\u0c27\0\u0c64\0\u0ca1\0\u0cde"+
    "\0\u0d1b\0\u0d58\0\u0d95\0\u0dd2\0\u0e0f\0\u0e4c\0\u057b\0\u0e89"+
    "\0\u0ec6\0\u0f03\0\u0f40\0\u0f7d\0\u0fba\0\u0ff7\0\u1034\0\u1071"+
    "\0\u10ae\0\u10eb\0\u1128\0\u1165\0\u11a2\0\u11df\0\75\0\u121c"+
    "\0\u1259\0\75\0\u1296\0\u12d3\0\u057b\0\u057b\0\u057b\0\u057b"+
    "\0\u057b\0\u057b\0\u057b\0\u1310\0\u134d\0\u057b\0\u138a\0\u057b"+
    "\0\u13c7\0\u057b\0\u1404\0\u1441\0\u147e\0\u14bb\0\u14f8\0\u1535"+
    "\0\u1572\0\u15af\0\u15ec\0\u057b\0\u1629\0\u1666\0\u16a3\0\u057b"+
    "\0\u16e0\0\u171d\0\u057b\0\u175a\0\u1797\0\u17d4\0\u1811\0\u184e"+
    "\0\u188b\0\u18c8\0\u1905\0\u1942\0\u057b\0\u057b\0\u057b\0\u197f"+
    "\0\u1165\0\u19bc\0\u121c\0\u19f9\0\u1a36\0\u057b\0\u057b\0\u1a73"+
    "\0\u057b\0\u057b\0\u1ab0\0\u057b\0\u057b\0\u1aed\0\u1b2a\0\u1b67"+
    "\0\u1ba4\0\u057b\0\u1be1\0\u057b\0\u1c1e\0\u057b\0\u1c5b\0\u1c98"+
    "\0\u057b\0\u1cd5\0\u1d12\0\u1d4f\0\u1d8c\0\u057b\0\u1dc9\0\u057b"+
    "\0\u1e06\0\u1e43\0\u1e80\0\u057b\0\u1ebd\0\u1efa\0\u1f37\0\u1f74"+
    "\0\u1fb1\0\u1fee\0\u202b\0\u2068\0\u20a5\0\u20e2\0\u211f\0\u215c"+
    "\0\u2199\0\u21d6\0\u2213\0\u2250\0\u057b\0\u228d\0\u22ca\0\u2307"+
    "\0\u2344\0\u057b\0\u2381\0\u23be\0\u23fb\0\u2438\0\u2475\0\u24b2"+
    "\0\u057b\0\u24ef\0\u252c\0\u057b\0\u2569\0\u25a6\0\u057b\0\u057b"+
    "\0\u25e3\0\u057b\0\u057b\0\u2620\0\u265d\0\u269a\0\u26d7\0\u2714"+
    "\0\u057b\0\u057b\0\u057b\0\u2751\0\u278e\0\u057b\0\u057b\0\u057b"+
    "\0\u27cb\0\u2808\0\u2845\0\u057b\0\u057b\0\u057b";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[246];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\3\46\1\47\1\50\3\46"+
    "\1\51\1\52\1\53\3\46\1\54\1\55\1\2\1\56"+
    "\1\2\1\57\2\46\1\2\2\56\100\0\1\60\100\0"+
    "\1\61\76\0\1\62\1\63\74\0\1\64\4\0\1\65"+
    "\63\0\1\66\5\0\1\62\72\0\1\67\2\0\1\15"+
    "\74\0\1\70\1\71\1\72\67\0\1\73\3\0\1\74"+
    "\103\0\1\75\77\0\1\46\1\76\1\77\3\46\1\100"+
    "\1\101\24\46\2\0\5\46\32\0\13\46\1\102\20\46"+
    "\2\0\5\46\32\0\11\46\1\103\1\104\1\105\3\46"+
    "\1\106\14\46\2\0\5\46\32\0\14\46\1\107\17\46"+
    "\2\0\5\46\32\0\13\46\1\110\20\46\2\0\5\46"+
    "\32\0\14\46\1\111\17\46\2\0\5\46\32\0\11\46"+
    "\1\112\5\46\1\113\14\46\2\0\5\46\32\0\17\46"+
    "\1\114\14\46\2\0\5\46\32\0\12\46\1\115\21\46"+
    "\2\0\5\46\32\0\6\46\1\116\1\117\11\46\1\120"+
    "\12\46\2\0\5\46\32\0\7\46\1\121\1\122\7\46"+
    "\1\123\4\46\1\124\6\46\2\0\5\46\32\0\7\46"+
    "\1\125\24\46\2\0\5\46\32\0\34\46\2\0\5\46"+
    "\32\0\1\46\1\126\2\46\1\127\2\46\1\130\14\46"+
    "\1\131\7\46\2\0\5\46\32\0\1\132\11\46\1\133"+
    "\4\46\1\134\14\46\2\0\5\46\32\0\1\135\3\46"+
    "\1\136\27\46\2\0\5\46\32\0\1\137\12\46\1\140"+
    "\3\46\1\141\14\46\2\0\5\46\32\0\7\46\1\142"+
    "\24\46\2\0\5\46\32\0\3\46\1\143\30\46\2\0"+
    "\5\46\2\0\63\55\1\144\1\145\10\55\30\0\34\146"+
    "\2\0\1\146\1\57\1\0\1\146\3\0\65\62\1\56"+
    "\5\62\1\56\1\62\12\0\1\147\62\0\6\150\1\151"+
    "\66\150\12\0\1\152\112\0\2\46\1\153\31\46\2\0"+
    "\5\46\32\0\2\46\1\154\31\46\2\0\5\46\32\0"+
    "\6\46\1\155\25\46\2\0\5\46\32\0\10\46\1\156"+
    "\23\46\2\0\5\46\32\0\3\46\1\157\30\46\2\0"+
    "\5\46\32\0\3\46\1\160\24\46\1\161\3\46\2\0"+
    "\5\46\32\0\31\46\1\162\2\46\2\0\5\46\32\0"+
    "\20\46\1\163\13\46\2\0\5\46\32\0\20\46\1\164"+
    "\13\46\2\0\5\46\32\0\12\46\1\165\21\46\2\0"+
    "\5\46\32\0\7\46\1\166\24\46\2\0\5\46\32\0"+
    "\11\46\1\167\22\46\2\0\5\46\32\0\3\46\1\170"+
    "\30\46\2\0\5\46\32\0\7\46\1\171\24\46\2\0"+
    "\5\46\32\0\3\46\1\172\3\46\1\173\24\46\2\0"+
    "\5\46\32\0\2\46\1\174\31\46\2\0\5\46\32\0"+
    "\2\46\1\175\31\46\2\0\5\46\32\0\13\46\1\176"+
    "\20\46\2\0\5\46\32\0\1\177\2\46\1\200\10\46"+
    "\1\201\7\46\1\202\7\46\2\0\5\46\32\0\2\46"+
    "\1\203\1\204\1\46\1\205\26\46\2\0\5\46\32\0"+
    "\11\46\1\206\22\46\2\0\5\46\32\0\24\46\1\207"+
    "\7\46\2\0\5\46\32\0\25\46\1\210\6\46\2\0"+
    "\5\46\32\0\12\46\1\211\21\46\2\0\5\46\32\0"+
    "\16\46\1\212\15\46\2\0\5\46\32\0\11\46\1\213"+
    "\22\46\2\0\5\46\32\0\3\46\1\214\5\46\1\215"+
    "\22\46\2\0\5\46\32\0\21\46\1\216\12\46\2\0"+
    "\5\46\32\0\7\46\1\217\24\46\2\0\5\46\32\0"+
    "\10\46\1\220\23\46\2\0\5\46\32\0\4\46\1\221"+
    "\27\46\2\0\5\46\32\0\11\46\1\222\1\223\21\46"+
    "\2\0\5\46\32\0\5\46\1\224\26\46\2\0\5\46"+
    "\32\0\7\46\1\225\24\46\2\0\5\46\32\0\4\46"+
    "\1\226\27\46\2\0\5\46\32\0\3\46\1\227\30\46"+
    "\2\0\5\46\32\0\4\46\1\230\27\46\2\0\5\46"+
    "\32\0\34\231\2\0\2\231\1\0\1\231\3\0\65\55"+
    "\1\0\7\55\30\0\34\146\2\0\2\146\1\0\1\146"+
    "\3\0\6\150\1\232\74\150\1\232\5\150\1\233\60\150"+
    "\30\0\3\46\1\234\30\46\2\0\5\46\32\0\11\46"+
    "\1\235\22\46\2\0\5\46\32\0\11\46\1\236\22\46"+
    "\2\0\5\46\32\0\2\46\1\237\31\46\2\0\5\46"+
    "\32\0\5\46\1\240\26\46\2\0\5\46\32\0\11\46"+
    "\1\241\22\46\2\0\5\46\32\0\11\46\1\242\22\46"+
    "\2\0\5\46\32\0\16\46\1\243\15\46\2\0\5\46"+
    "\32\0\11\46\1\244\22\46\2\0\5\46\32\0\20\46"+
    "\1\245\13\46\2\0\5\46\32\0\5\46\1\246\26\46"+
    "\2\0\5\46\32\0\11\46\1\247\22\46\2\0\5\46"+
    "\32\0\1\250\33\46\2\0\5\46\32\0\11\46\1\251"+
    "\22\46\2\0\5\46\32\0\3\46\1\252\30\46\2\0"+
    "\5\46\32\0\6\46\1\253\25\46\2\0\5\46\32\0"+
    "\7\46\1\254\24\46\2\0\5\46\32\0\6\46\1\255"+
    "\25\46\2\0\5\46\32\0\23\46\1\256\10\46\2\0"+
    "\5\46\32\0\11\46\1\257\22\46\2\0\5\46\32\0"+
    "\12\46\1\260\21\46\2\0\5\46\32\0\7\46\1\261"+
    "\24\46\2\0\5\46\32\0\12\46\1\262\21\46\2\0"+
    "\5\46\32\0\12\46\1\263\21\46\2\0\5\46\32\0"+
    "\13\46\1\264\20\46\2\0\5\46\32\0\3\46\1\265"+
    "\30\46\2\0\5\46\32\0\10\46\1\266\23\46\2\0"+
    "\5\46\32\0\23\46\1\267\10\46\2\0\5\46\32\0"+
    "\3\46\1\270\30\46\2\0\5\46\32\0\12\46\1\271"+
    "\21\46\2\0\5\46\2\0\6\150\1\232\5\150\1\56"+
    "\60\150\30\0\4\46\1\272\27\46\2\0\5\46\32\0"+
    "\4\46\1\273\27\46\2\0\5\46\32\0\15\46\1\274"+
    "\16\46\2\0\5\46\32\0\17\46\1\275\14\46\2\0"+
    "\5\46\32\0\3\46\1\276\30\46\2\0\5\46\32\0"+
    "\7\46\1\277\24\46\2\0\5\46\32\0\13\46\1\300"+
    "\20\46\2\0\5\46\32\0\5\46\1\301\26\46\2\0"+
    "\5\46\32\0\13\46\1\302\20\46\2\0\5\46\32\0"+
    "\12\46\1\303\21\46\2\0\5\46\32\0\5\46\1\304"+
    "\26\46\2\0\5\46\32\0\20\46\1\305\13\46\2\0"+
    "\5\46\32\0\20\46\1\306\13\46\2\0\5\46\32\0"+
    "\20\46\1\307\13\46\2\0\5\46\32\0\6\46\1\310"+
    "\25\46\2\0\5\46\32\0\12\46\1\311\21\46\2\0"+
    "\5\46\32\0\1\312\33\46\2\0\5\46\32\0\7\46"+
    "\1\313\24\46\2\0\5\46\32\0\1\314\33\46\2\0"+
    "\5\46\32\0\3\46\1\315\30\46\2\0\5\46\32\0"+
    "\12\46\1\316\21\46\2\0\5\46\32\0\6\46\1\317"+
    "\25\46\2\0\5\46\32\0\10\46\1\320\23\46\2\0"+
    "\5\46\32\0\2\46\1\321\31\46\2\0\5\46\32\0"+
    "\3\46\1\322\30\46\2\0\5\46\32\0\10\46\1\323"+
    "\23\46\2\0\5\46\32\0\11\46\1\324\22\46\2\0"+
    "\5\46\32\0\3\46\1\325\30\46\2\0\5\46\32\0"+
    "\12\46\1\326\21\46\2\0\5\46\32\0\12\46\1\327"+
    "\21\46\2\0\5\46\32\0\12\46\1\330\21\46\2\0"+
    "\5\46\32\0\11\46\1\331\22\46\2\0\5\46\32\0"+
    "\3\46\1\332\30\46\2\0\5\46\32\0\3\46\1\333"+
    "\30\46\2\0\5\46\32\0\31\46\1\334\2\46\2\0"+
    "\5\46\32\0\5\46\1\335\26\46\2\0\5\46\32\0"+
    "\7\46\1\336\24\46\2\0\5\46\32\0\22\46\1\337"+
    "\11\46\2\0\5\46\32\0\2\46\1\340\31\46\2\0"+
    "\5\46\32\0\3\46\1\341\30\46\2\0\5\46\32\0"+
    "\11\46\1\342\22\46\2\0\5\46\32\0\2\46\1\343"+
    "\31\46\2\0\5\46\32\0\12\46\1\344\21\46\2\0"+
    "\5\46\32\0\27\46\1\345\4\46\2\0\5\46\32\0"+
    "\27\46\1\346\4\46\2\0\5\46\32\0\27\46\1\347"+
    "\4\46\2\0\5\46\32\0\12\46\1\350\21\46\2\0"+
    "\5\46\32\0\11\46\1\351\22\46\2\0\5\46\32\0"+
    "\3\46\1\352\30\46\2\0\5\46\32\0\3\46\1\353"+
    "\30\46\2\0\5\46\32\0\12\46\1\354\21\46\2\0"+
    "\5\46\32\0\23\46\1\355\10\46\2\0\5\46\32\0"+
    "\11\46\1\356\22\46\2\0\5\46\32\0\11\46\1\357"+
    "\22\46\2\0\5\46\32\0\11\46\1\360\22\46\2\0"+
    "\5\46\32\0\17\46\1\361\14\46\2\0\5\46\32\0"+
    "\23\46\1\362\10\46\2\0\5\46\32\0\11\46\1\363"+
    "\22\46\2\0\5\46\32\0\7\46\1\364\24\46\2\0"+
    "\5\46\32\0\11\46\1\365\22\46\2\0\5\46\32\0"+
    "\2\46\1\366\31\46\2\0\5\46\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[10370];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\3\11\1\1\3\11\1\1\1\11\2\1\1\11"+
    "\4\1\5\11\1\1\2\11\24\1\1\11\1\1\2\11"+
    "\1\1\1\11\1\1\1\11\1\0\3\11\1\1\3\11"+
    "\47\1\1\0\1\1\1\11\2\0\1\11\57\1\1\0"+
    "\134\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[246];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
 public String alloy_filename="";
 public int alloy_lineoffset=0; // If not zero, it is added to the current LINE NUMBER
 public List<Object> alloy_seenDollar;
 public CompModule alloy_module;
 private final Pos alloy_here(String txt) {
    return new Pos(alloy_filename,yycolumn+1,yyline+1+alloy_lineoffset,yycolumn+txt.length(),yyline+1);
 }
 private final Symbol alloy_sym(String txt, int type) {
    Pos p = alloy_here(txt); return new Symbol(type, p, p);
 }
 private final Symbol alloy_string(String txt) throws Err {
    Pos p = alloy_here(txt);
    if (!Version.experimental) throw new ErrorSyntax(p, "String literal is not currently supported.");
    StringBuilder sb = new StringBuilder(txt.length());
    for(int i=0; i<txt.length(); i++) {
       char c = txt.charAt(i);
       if (c=='\r' || c=='\n') throw new ErrorSyntax(p, "String literal cannot span multiple lines; use \\n instead.");
       if (c=='\\') {
          i++;
          if (i>=txt.length()) throw new ErrorSyntax(p, "String literal cannot end with a single \\");
          c = txt.charAt(i);
          if (c=='n') c='\n'; else if (c!='\'' && c!='\"' && c!='\\') throw new ErrorSyntax(p, "String literal currenty only supports\nfour escape sequences: \\\\, \\n, \\\', and \\\"");
       }
       sb.append(c);
    }
    txt = sb.toString();
    if (txt.length()==2) throw new ErrorSyntax(p, "Empty string is not allowed; try rewriting your model to use an empty set instead.");
    return new Symbol(CompSym.STR, p, ExprConstant.Op.STRING.make(p, txt));
 }
 private final Symbol alloy_id(String txt) throws Err {
    Pos p=alloy_here(txt);
    if (alloy_seenDollar.size()==0 && txt.indexOf('$')>=0) alloy_seenDollar.add(null);
    return new Symbol(CompSym.ID, p, ExprVar.make(p,txt));
 }
 private final Symbol alloy_num(String txt) throws Err {
    Pos p=alloy_here(txt);
    int n=0;
    try {
       n=Integer.parseInt(txt);
    } catch(NumberFormatException ex) {
       throw new ErrorSyntax(p, "The number "+txt+" is too large to be stored in a Java integer");
    }
    return new Symbol(CompSym.NUMBER, p, ExprConstant.Op.NUMBER.make(p, n));
 }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public CompLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public CompLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1766) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
 * @throws Err 
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException, Err {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 4: 
          { return alloy_sym(yytext(), CompSym.AMPERSAND   );
          }
        case 90: break;
        case 50: 
          { return alloy_sym(yytext(), CompSym.SEQ         );
          }
        case 91: break;
        case 38: 
          { return alloy_sym(yytext(), CompSym.IMPLIES     );
          }
        case 92: break;
        case 23: 
          { return alloy_sym(yytext(), CompSym.RBRACE      );
          }
        case 93: break;
        case 81: 
          { return alloy_sym(yytext(), CompSym.EXACTLY     );
          }
        case 94: break;
        case 53: 
          { return alloy_sym(yytext(), CompSym.RUN         );
          }
        case 95: break;
        case 36: 
          { return alloy_sym(yytext(), CompSym.SHL         );
          }
        case 96: break;
        case 35: 
          { return alloy_sym(yytext(), CompSym.DOMAIN      );
          }
        case 97: break;
        case 69: 
          { return alloy_sym(yytext(), CompSym.BOUND        );
          }
        case 98: break;
        case 60: 
          { return alloy_sym(yytext(), CompSym.SIGINT      );
          }
        case 99: break;
        case 24: 
          { return alloy_sym(yytext(), CompSym.TILDE       );
          }
        case 100: break;
        case 21: 
          { return alloy_sym(yytext(), CompSym.LBRACE      );
          }
        case 101: break;
        case 7: 
          { return alloy_sym(yytext(), CompSym.STAR        );
          }
        case 102: break;
        case 30: 
          { return alloy_sym(yytext(), CompSym.PLUSPLUS    );
          }
        case 103: break;
        case 58: 
          { return alloy_sym(yytext(), CompSym.FUN         );
          }
        case 104: break;
        case 80: 
          { return alloy_sym(yytext(), CompSym.STRING      );
          }
        case 105: break;
        case 55: 
          { return alloy_sym(yytext(), CompSym.EXH         );
          }
        case 106: break;
        case 56: 
          { return alloy_sym(yytext(), CompSym.INT         );
          }
        case 107: break;
        case 51: 
          { return alloy_sym(yytext(), CompSym.SIG         );
          }
        case 108: break;
        case 74: 
          { return alloy_sym(yytext(), CompSym.PRED        );
          }
        case 109: break;
        case 25: 
          { return alloy_id  (yytext());
          }
        case 110: break;
        case 64: 
          { return alloy_sym(yytext(), CompSym.LONE        );
          }
        case 111: break;
        case 41: 
          { return alloy_sym(yytext(), CompSym.NO          );
          }
        case 112: break;
        case 9: 
          { return alloy_sym(yytext(), CompSym.COMMA       );
          }
        case 113: break;
        case 40: 
          { return alloy_sym(yytext(), CompSym.AS          );
          }
        case 114: break;
        case 63: 
          { return alloy_sym(yytext(), CompSym.THIS        );
          }
        case 115: break;
        case 13: 
          { return alloy_sym(yytext(), CompSym.SLASH       );
          }
        case 116: break;
        case 48: 
          { return alloy_sym(yytext(), CompSym.BUT         );
          }
        case 117: break;
        case 43: 
          { return alloy_string(yytext());
          }
        case 118: break;
        case 66: 
          { return alloy_sym(yytext(), CompSym.DISJ        );
          }
        case 119: break;
        case 32: 
          { return alloy_sym(yytext(), CompSym.SHA         );
          }
        case 120: break;
        case 39: 
          { return alloy_sym(yytext(), CompSym.OR          );
          }
        case 121: break;
        case 45: 
          { return alloy_sym(yytext(), CompSym.SHR         );
          }
        case 122: break;
        case 84: 
          { return alloy_sym(yytext(), CompSym.PRIVATE     );
          }
        case 123: break;
        case 31: 
          { return alloy_sym(yytext(), CompSym.ARROW       );
          }
        case 124: break;
        case 33: 
          { return alloy_sym(yytext(), CompSym.GTE         );
          }
        case 125: break;
        case 20: 
          { return alloy_sym(yytext(), CompSym.CARET       );
          }
        case 126: break;
        case 46: 
          { return alloy_sym(yytext(), CompSym.IFF         );
          }
        case 127: break;
        case 67: 
          { return alloy_sym(yytext(), CompSym.ELSE        );
          }
        case 128: break;
        case 3: 
          { return alloy_sym(yytext(), CompSym.HASH        );
          }
        case 129: break;
        case 12: 
          { return alloy_sym(yytext(), CompSym.DOT         );
          }
        case 130: break;
        case 22: 
          { return alloy_sym(yytext(), CompSym.BAR         );
          }
        case 131: break;
        case 78: 
          { return alloy_sym(yytext(), CompSym.EXPECT      );
          }
        case 132: break;
        case 8: 
          { return alloy_sym(yytext(), CompSym.PLUS        );
          }
        case 133: break;
        case 37: 
          { return alloy_sym(yytext(), CompSym.LTE         );
          }
        case 134: break;
        case 57: 
          { return alloy_sym(yytext(), CompSym.ONE         );
          }
        case 135: break;
        case 72: 
          { return alloy_sym(yytext(), CompSym.OPEN        );
          }
        case 136: break;
        case 11: 
          { return alloy_sym(yytext(), CompSym.GT          );
          }
        case 137: break;
        case 79: 
          { return alloy_sym(yytext(), CompSym.MODULE      );
          }
        case 138: break;
        case 14: 
          { return alloy_sym(yytext(), CompSym.COLON       );
          }
        case 139: break;
        case 52: 
          { return alloy_sym(yytext(), CompSym.SUM         );
          }
        case 140: break;
        case 73: 
          { return alloy_sym(yytext(), CompSym.PART        );
          }
        case 141: break;
        case 16: 
          { return alloy_sym(yytext(), CompSym.EQUALS      );
          }
        case 142: break;
        case 82: 
          { return alloy_sym(yytext(), CompSym.EXTENDS     );
          }
        case 143: break;
        case 1: 
          { throw new ErrorSyntax(alloy_here(" "), "Syntax error at the "+yytext()+" character.");
          }
        case 144: break;
        case 26: 
          { throw new ErrorSyntax(alloy_here(yytext()),"String literal is missing its closing \" character");
          }
        case 145: break;
        case 86: 
          { return alloy_sym(yytext(), CompSym.OPTIMIZE    );
          }
        case 146: break;
        case 59: 
          { return alloy_sym(yytext(), CompSym.FOR         );
          }
        case 147: break;
        case 28: 
          { return alloy_num (yytext());
          }
        case 148: break;
        case 88: 
          { return alloy_sym(yytext(), CompSym.MINIMIZE    );
          }
        case 149: break;
        case 70: 
          { return alloy_sym(yytext(), CompSym.IDEN        );
          }
        case 150: break;
        case 15: 
          { return alloy_sym(yytext(), CompSym.LT          );
          }
        case 151: break;
        case 17: 
          { return alloy_sym(yytext(), CompSym.AT          );
          }
        case 152: break;
        case 34: 
          { return alloy_sym(yytext(), CompSym.RANGE       );
          }
        case 153: break;
        case 87: 
          { return alloy_sym(yytext(), CompSym.MAXIMIZE    );
          }
        case 154: break;
        case 83: 
          { return alloy_sym(yytext(), CompSym.INCLUDE     );
          }
        case 155: break;
        case 71: 
          { return alloy_sym(yytext(), CompSym.UNIV        );
          }
        case 156: break;
        case 2: 
          { return alloy_sym(yytext(), CompSym.NOT         );
          }
        case 157: break;
        case 49: 
          { return alloy_sym(yytext(), CompSym.SET         );
          }
        case 158: break;
        case 6: 
          { return alloy_sym(yytext(), CompSym.RPAREN      );
          }
        case 159: break;
        case 42: 
          { return alloy_sym(yytext(), CompSym.IN          );
          }
        case 160: break;
        case 76: 
          { return alloy_sym(yytext(), CompSym.CHECK       );
          }
        case 161: break;
        case 29: 
          { return alloy_sym(yytext(), CompSym.AND         );
          }
        case 162: break;
        case 62: 
          { return alloy_sym(yytext(), CompSym.SOME        );
          }
        case 163: break;
        case 75: 
          { return alloy_sym(yytext(), CompSym.FACT        );
          }
        case 164: break;
        case 10: 
          { return alloy_sym(yytext(), CompSym.MINUS       );
          }
        case 165: break;
        case 5: 
          { return alloy_sym(yytext(), CompSym.LPAREN      );
          }
        case 166: break;
        case 65: 
          { return alloy_sym(yytext(), CompSym.NONE        );
          }
        case 167: break;
        case 18: 
          { return alloy_sym(yytext(), CompSym.LBRACKET    );
          }
        case 168: break;
        case 19: 
          { return alloy_sym(yytext(), CompSym.RBRACKET    );
          }
        case 169: break;
        case 68: 
          { return alloy_sym(yytext(), CompSym.ENUM        );
          }
        case 170: break;
        case 47: 
          { return alloy_sym(yytext(), CompSym.ALL         );
          }
        case 171: break;
        case 85: 
          { return alloy_sym(yytext(), CompSym.ABSTRACT    );
          }
        case 172: break;
        case 77: 
          { return alloy_sym(yytext(), CompSym.ASSERT      );
          }
        case 173: break;
        case 61: 
          { throw new ErrorSyntax(alloy_here(yytext()),"String literal cannot be followed by a legal identifier character.");
          }
        case 174: break;
        case 89: 
          { return alloy_sym(yytext(), CompSym.OBJECTIVES  );
          }
        case 175: break;
        case 54: 
          { return alloy_sym(yytext(), CompSym.LET         );
          }
        case 176: break;
        case 27: 
          { 
          }
        case 177: break;
        case 44: 
          { throw new ErrorSyntax(alloy_here(yytext()),"Name cannot start with a number.");
          }
        case 178: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {   return new Symbol(CompSym.EOF, alloy_here(" "), alloy_here(" "));
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
